asm_linkage.o: asm_linkage.S asm_linkage.h
boot.o: boot.S multiboot.h x86_desc.h types.h
paging_function.o: paging_function.S
system_call_linkage.o: system_call_linkage.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handler.o: exception_handler.c idt.h x86_desc.h types.h lib.h \
  exception_handler.h asm_linkage.h
file_system.o: file_system.c systemcall.h types.h lib.h file_system.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h exception_handler.h \
  asm_linkage.h keyboard.h rtc.h systemcall.h file_system.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h exception_handler.h asm_linkage.h paging.h keyboard.h \
  rtc.h file_system.h systemcall.h terminal.h
keyboard.o: keyboard.c keyboard.h types.h terminal.h systemcall.h lib.h \
  file_system.h i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h terminal.h keyboard.h systemcall.h \
  lib.h file_system.h
pit.o: pit.c pit.h i8259.h types.h lib.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
systemcall.o: systemcall.c systemcall.h types.h lib.h file_system.h rtc.h \
  paging.h terminal.h keyboard.h x86_desc.h
terminal.o: terminal.c terminal.h keyboard.h types.h systemcall.h lib.h \
  file_system.h i8259.h paging.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h systemcall.h \
  file_system.h terminal.h keyboard.h rtc.h paging.h idt.h \
  exception_handler.h asm_linkage.h
